import type { Session } from '../types'

// Fake sessions — we'll replace this with real API data later
// This lets us build and style the UI without a backend
export const mockSessions: Session[] = [
  {
    id: '1',
    title: 'AI Tutoring Platform',
    ideaText: 'A personalized AI tutor for high school students',
    status: 'COMPLETE',
    version: 3,
    overallResilienceScore: 84,
    createdAt: '2024-03-01T10:00:00Z',
    completedAt: '2024-03-01T11:30:00Z',
  },
  {
    id: '2',
    title: 'Hyperlocal Grocery Delivery',
    ideaText: 'Same-hour grocery delivery from local stores',
    status: 'DEFENDING',
    version: 2,
    overallResilienceScore: 61,
    createdAt: '2024-03-03T14:00:00Z',
    completedAt: null,
  },
  {
    id: '3',
    title: 'B2B SaaS for Restaurants',
    ideaText: 'Inventory management tool for small restaurants',
    status: 'ATTACKING',
    version: 1,
    overallResilienceScore: null,
    createdAt: '2024-03-05T09:00:00Z',
    completedAt: null,
  },
  {
    id: '4',
    title: 'Freelancer Insurance',
    ideaText: 'Affordable health insurance bundles for freelancers',
    status: 'COMPLETE',
    version: 2,
    overallResilienceScore: 72,
    createdAt: '2024-02-28T16:00:00Z',
    completedAt: '2024-02-28T17:45:00Z',
  },
  {
    id: '5',
    title: 'Remote Team Culture Tool',
    ideaText: 'Platform to build culture in fully remote companies',
    status: 'DRAFT',
    version: 1,
    overallResilienceScore: null,
    createdAt: '2024-03-06T08:00:00Z',
    completedAt: null,
  },
]

import type { Attack } from '../types';

// Add this below mockSessions
export const mockAttacks: Attack[] = [
  {
    id: '1',
    sessionId: '1',
    agentType: 'COMPETITOR',
    title: 'Google enters the market with a free tier',
    description: 'Google has the distribution, brand trust, and AI infrastructure to launch a competing product at zero cost to users, immediately undercutting your pricing model.',
    evidence: 'Google launched Google Classroom for free in 2014, killing several EdTech startups within 18 months.',
    severity: 'critical',
    likelihood: 0.72,
    status: 'UNDEFENDED',
    defenseScore: null,
  },
  {
    id: '2',
    sessionId: '1',
    agentType: 'SKEPTIC',
    title: 'Trainers lack technical adoption willingness',
    description: 'Your assumption that 50,000 trainers will pay $49/month ignores that the average independent trainer earns under $2,000/month and is resistant to new software tools.',
    evidence: 'Mindbody reported 67% churn in first 90 days among solo fitness professionals.',
    severity: 'high',
    likelihood: 0.81,
    status: 'UNDEFENDED',
    defenseScore: null,
  },
  {
    id: '3',
    sessionId: '1',
    agentType: 'CUSTOMER',
    title: 'Clients won\'t download another app',
    description: 'End clients (the trainers\' customers) already suffer from app fatigue. Asking them to download a white-labeled app creates friction that trainers will blame on your platform.',
    evidence: 'Average smartphone user downloads 0 new apps per month (Comscore, 2023).',
    severity: 'high',
    likelihood: 0.68,
    status: 'UNDEFENDED',
    defenseScore: null,
  },
  {
    id: '4',
    sessionId: '1',
    agentType: 'SABOTEUR',
    title: 'Payment infrastructure fails in Indian market',
    description: 'Handling payments for 50,000 trainers across India requires RBI compliance, GST integration, and UPI support. This is a 6-month engineering project minimum, not a feature.',
    evidence: 'Razorpay took 14 months to achieve full RBI compliance for marketplace payouts.',
    severity: 'critical',
    likelihood: 0.59,
    status: 'UNDEFENDED',
    defenseScore: null,
  },
]